apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctiondetails
  labels:
    app: auctiondetails
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auctiondetails
  template:
    metadata:
      labels:
        app: auctiondetails
    spec:
      containers: # todo name and image
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80