apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: mongodb
  name: mongodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo
          imagePullPolicy: Always
          name: mongo
          ports:
            - containerPort: 27017
              protocol: TCP
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: default
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
