apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: useraccount
  name: useraccount
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: useraccount
  template:
    metadata:
      labels:
        app: useraccount
    spec:
      containers:
        - env:
          - name: backend
            value: mongodb://mongouseraccounts:27017/useraccounts
          image: auctionbackend-useraccount:latest
          imagePullPolicy: Never
          name: auctionbackend-useraccount
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: useraccount
  name: useraccount
  namespace: default
spec:
  ports:
  - nodePort: 30198
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: useraccount
  type: NodePort
