apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auctionroommanager
  name: auctionroommanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctionroommanager
  template:
    metadata:
      labels:
        app: auctionroommanager
    spec:
      containers:
          - image: auctionbackend-auctionroommanager:latest
            imagePullPolicy: Never
            name: auctionbackend-auctionroommanager
            ports:
            - containerPort: 9000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auctionroommanager
  name: auctionroommanager
  namespace: default
spec:
  ports:
  - nodePort: 30199
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: auctionroommanager
  type: NodePort