apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auctiondetails
  name: auctiondetails
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctiondetails
  template:
    metadata:
      labels:
        app: auctiondetails
    spec:
      containers:
        - env:
          - name: PORT
            value: "8080"
          - name: backend
            value: mongodb://mongodb:27017/auctiondetails
          image: auctionbackend-auctiondetails:latest
          imagePullPolicy: Never
          name: auctionbackend-auctiondetails
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auctiondetails
  name: auctiondetails
  namespace: default
spec:
  ports:
  - nodePort: 30200
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: auctiondetails
  type: NodePort
