apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auctionroom
  name: auctionroom
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auctionroom
  template:
    metadata:
      labels:
        app: auctionroom
    spec:
      containers:
        - image: auctionbackend-auctionroom:latest
          imagePullPolicy: Never
          name: auctionbackend-auctionroom
          ports:
          - containerPort: 9090
            protocol: TCP
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auctionroom
  name: auctionroom
  namespace: default
spec:
  ports:
  - nodePort: 30233
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: auctionroom
  type: NodePort
