apiVersion: v1
kind: Service
metadata:
  name: auctiondetails
  labels:
    run: auctiondetails
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80 
    nodePort: 31500 
  type: NodePort
  selector:
    run: auctiondetails
    
