apiVersion: apps/v1
kind: Deployment
metadata:
  name: auctionbackend-auctionroommanager
spec:
  selector:
    matchLabels:
      run: auctionbackend-auctionroommanager
  replicas: 1
  template:
    metadata:
      labels:
        run: auctionbackend-auctionroommanager
    spec:
      containers:
      - name: auctionbackend-auctionroommanager
        image: auctionbackend-auctionroommanager
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: auctionbackend-auctionroommanager
  labels:
    run: auctionbackend-auctionroommanager
spec:
  selector:
    run: auctionbackend-auctionroommanager
  type: NodePort
  ports:
    - port: 8080
    targetPort: 9000  
    nodePort: 30001
  selector:
    run: auctionbackend-auctionroommanager
# apiVersion: v1
# kind: Service
metadata:
  name: auctionbackend-auctionroommanager
spec:
  type: NodePort
  selector:
    run: auctionbackend-auctionroommanager
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: auctionbackend-auctiondetails
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auctionbackend-auctiondetails
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30