apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongoauctiondetails
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: mongoauctiondetails
  name: mongoauctiondetails
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoauctiondetails
  template:
    metadata:
      labels:
        app: mongoauctiondetails
    spec:
      containers:
        - image: mongo
          imagePullPolicy: Always
          name: mongoauctiondetails
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongoauctiondetails
              mountPath: /data/auctiondetails
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: mongoauctiondetails
          persistentVolumeClaim:
            claimName: mongoauctiondetails

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongoauctiondetails
  name: mongoauctiondetails
  namespace: default
spec:
  ports:
    - port: 27018
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongoauctiondetails
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongoauctiondetails
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongoauctiondetails
  targetCPUUtilizationPercentage: 80
