apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongouseraccounts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: mongouseraccounts
  name: mongouseraccounts
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongouseraccounts
  template:
    metadata:
      labels:
        app: mongouseraccounts
    spec:
      containers:
        - image: mongo
          imagePullPolicy: Always
          name: mongouseraccounts
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongouseraccounts
              mountPath: /data/useraccounts
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: mongouseraccounts
          persistentVolumeClaim:
            claimName: mongouseraccounts

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongouseraccounts
  name: mongouseraccounts
  namespace: default
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongouseraccounts
  type: ClusterIP

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongouseraccounts
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongouseraccounts
  targetCPUUtilizationPercentage: 80