apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aggregatesvr
  name: aggregatesvr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregatesvr
  template:
    metadata:
      labels:
        app: aggregatesvr
    spec:
      containers:
        - image: aggregatesvr:latest
          imagePullPolicy: Never
          name: aggregatesvr
          ports:
          - containerPort: 8085
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aggregatesvr
  name: aggregatesvr
  namespace: default
spec:
  ports:
  - nodePort: 30271
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: aggregatesvr
  type: NodePort
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aggregatesvr
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aggregatesvr
  targetCPUUtilizationPercentage: 80