name: Test api gateway url
on:
  push:
    branches:
      - main
jobs:
  run-postman:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Install Node on the runner
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
        node-version: '12.x'
    
    # Install the newman command line utility and also install the html extra reporter
    - name: Install newman
      run: |
       npm install -g newman

    # Run postman collection
    - name: Run postman tests for deployed ingress (api gateway) url
      run: |
        newman run ./k8/aggregate/aggregateproxy/postman/apigateway.postman_collection.json -e ./k8/aggregate/aggregateproxy/postman/tp-gke-apigateway.postman_environment.json

# https://theabodeofcode.com/running-postman-collections-in-github-action-workflows/